apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: meta-llama3-8b-instruct
  namespace: nim-service
spec:
  expose:
    ingress:
      enabled: true
      spec:
        rules:
          - host: meta-llama3-8b-instruct.apps.ai-dev03.kni.syseng.devcluster.openshift.com
            http:
              paths:
                - backend:
                    service:
                      name: meta-llama3-8b-instruct
                      port:
                        number: 8000
                  path: /v1/chat/completions
                  pathType: Prefix
    service:
      port: 8000
      type: ClusterIP
  authSecret: ngc-api-secret
  image:
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
    repository: nvcr.io/nim/meta/llama3-8b-instruct
    tag: 1.0.3
  storage:
    nimCache: {}
    pvc:
      create: true
      size: 20Gi
      storageClass: gp3-csi
      volumeAccessMode: ReadWriteOnce
  replicas: 1