apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: meta-llama-3-2-1b-instruct
  namespace: nemo
spec:
  image:
    repository: nvcr.io/nim/meta/llama-3.2-1b-instruct
    tag: "1.8"
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  authSecret: ngc-api-secret
  storage:
    nimCache:
      name: meta-llama-3-2-1b-instruct
      profile: '4f904d571fe60ff24695b5ee2aa42da58cb460787a968f1e8a09f5a7e862728d'
  replicas: 1
  resources:
    limits:
      nvidia.com/gpu: 1
  expose:
    service:
      type: ClusterIP
      port: 8000
  tolerations:
    - effect: NoSchedule
      key: p4-gpu
      operator: Exists
  nodeSelector:
    node.kubernetes.io/instance-type: p4d.24xlarge