apiVersion: v1
kind: ServiceAccount
metadata:
  name: "argo-workflows-executor"
  namespace: nemo
imagePullSecrets:
  - name: ngc-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "argo-workflows-executor-role"
  namespace: nemo
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - anyuid
    resources:
      - securitycontextconstraints
    verbs:
      - use
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "argo-workflows-executor-role-binding"
  namespace: nemo
subjects:
- kind: ServiceAccount
  name: "argo-workflows-executor"
roleRef:
  kind: Role
  name: "argo-workflows-executor-role"
  apiGroup: rbac.authorization.k8s.io
