apiVersion: v1
kind: ServiceAccount
metadata:
  name: milvus
  namespace: milvus-cluster

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scc-anyuid
  namespace: milvus-cluster
rules:
- apiGroups: ['security.openshift.io']
  resources: ['securitycontextconstraints']
  verbs: ['use']
  resourceNames: ['anyuid']

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: milvus-scc-anyuid-binding
  namespace: milvus-cluster
subjects:
- kind: ServiceAccount
  name: milvus
  namespace: milvus-cluster
roleRef:
  kind: Role
  name: scc-anyuid
  apiGroup: rbac.authorization.k8s.io