kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: evaluator
  namespace: nemo
spec:
  path: /
  to:
    kind: Service
    name: evaluator
    weight: 100
  port:
    targetPort: api
  wildcardPolicy: None
