---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    "app.kubernetes.io/name": "nemo-guardrail"
    "app.kubernetes.io/instance": "nemo-guardrail"
  name: nemo-guardrail
  namespace: nemo-service
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - nonroot
    verbs:
      - use