---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    "app.kubernetes.io/name": "nemo-guardrail"
    "app.kubernetes.io/instance": "nemo-guardrail"
  annotations:
    "openshift.io/scc": "nonroot"
  name: nemo-guardrail
  namespace: nemo-service
