apiVersion: v1
kind: ConfigMap
metadata:
  name: customizer-training-config
  namespace: nemo
data:
  training: |
    # Optional additional configuration for training jobs
    container_defaults:
      imagePullPolicy: IfNotPresent