apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scc-hostmount-anyuid
  namespace: nemo
rules:
- apiGroups: ['security.openshift.io']
  resources: ['securitycontextconstraints']
  verbs: ['use']
  resourceNames: ['hostmount-anyuid']

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: volcano-scc-hostmount-anyuid-binding
  namespace: nemo
subjects:
- kind: ServiceAccount
  name: volcano-scheduler
  namespace: nemo
roleRef:
  kind: Role
  name: scc-hostmount-anyuid
  apiGroup: rbac.authorization.k8s.io