apiVersion: apps.nvidia.com/v1alpha1
kind: NemoGuardrail
metadata:
  name: guardrail
  namespace: nemo
spec:
  # required if a NIM endpoint is hosted by NVIDIA
  configStore:
    pvc:
      name: "pvc-guardrail-config"
      create: true
      storageClass: "gp3-csi"
      volumeAccessMode: ReadWriteOnce
      size: "1Gi"
  nimEndpoint:
    baseURL: "http://meta-llama-3-2-1b-instruct.nemo.svc.cluster.local:8000/v1"
  expose:
    service:
      type: ClusterIP
      port: 8000
  image:
    repository: nvcr.io/nvidia/nemo-microservices/guardrails
    tag: "25.06"
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  metrics:
    serviceMonitor: {}
  replicas: 1
  resources:
    limits:
      cpu: "1"
      ephemeral-storage: 10Gi
