apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: nim-llama-3-1-8b-instruct-single
spec:
  model:
    uri: pvc://llama-3-1-8b-instruct-pvc
    name: meta-llama/llama-3.1-8b-instruct
  # Three replicas for load balancing
  replicas: 1
  router:
    route: {}
  template:
    containers:
      - name: main
        image: 'nvcr.io/nim/meta/llama-3.1-8b-instruct:latest'
        env:
          - name: NGC_API_KEY
            valueFrom:
              secretKeyRef:
                key: NGC_API_KEY
                name: ngc-api-secret
          - name: NIM_CACHE_PATH
            value: /mnt/models
        command: ["/bin/bash"]
        args: ["/opt/nim/start_server.sh"]
        ports:
          - containerPort: 8000
            protocol: TCP
        resources:
          limits:
            cpu: '12'
            memory: 64Gi
            nvidia.com/gpu: '1'
          requests:
            cpu: '12'
            memory: 32Gi
            nvidia.com/gpu: '1'
        readinessProbe:
          httpGet:
            path: /v1/health/ready
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /v1/health/live
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /v1/health/ready
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 120
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
    imagePullSecrets:
      - name: ngc-secret
    volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 16Gi
        name: dshm
    tolerations:
      - effect: NoSchedule
        key: p4de-gpu
        operator: Exists