apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: llama-3-2-nv-embedqa-1b-v2-single
spec:
  model:
    uri: pvc://llama-3-2-nv-embedqa-1b-v2-pvc
    name: nvidia/llama-nemotron-embed-1b-v2
  # Three replicas for load balancing
  replicas: 1
  router:
    route: {}
  template:
    containers:
      - name: main
        image: 'nvcr.io/nim/nvidia/llama-3.2-nv-embedqa-1b-v2:1.10'
        env:
          - name: NGC_API_KEY
            valueFrom:
              secretKeyRef:
                key: NGC_API_KEY
                name: ngc-api-secret
          - name: NIM_CACHE_PATH
            value: /mnt/models
          - name: NIM_SSL_MODE
            value: tls
          - name: NIM_SSL_KEY_PATH
            value: /var/run/kserve/tls/tls.key
          - name: NIM_SSL_CERT_PATH
            value: /var/run/kserve/tls/tls.crt
        command: ["/bin/bash"]
        args: ["/opt/nim/start_server.sh"]
        ports:
          - containerPort: 8000
            protocol: TCP
        resources:
          limits:
            cpu: '12'
            memory: 64Gi
            nvidia.com/gpu: '1'
          requests:
            cpu: '12'
            memory: 32Gi
            nvidia.com/gpu: '1'
        readinessProbe:
          httpGet:
            path: /v1/health/ready
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /v1/health/live
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /v1/health/ready
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 120
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
    imagePullSecrets:
      - name: ngc-secret
    volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 16Gi
        name: dshm
    tolerations:
      - effect: NoSchedule
        key: g6e-gpu
        operator: Exists