apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: llama-3-1-8b-instruct
  namespace: xieshen-nim
spec:
  resources:
    cpu: '0'
    memory: '0'
  source:
    ngc:
      authSecret: ngc-api-secret
      model:
        profiles:
          - 10e5c5c7b0037e16bc74e9ec32942256bf73fda9902c2697b6cbd8fe94b8b47e
      modelPuller: 'nvcr.io/nim/meta/llama-3.1-8b-instruct:1.15.4'
      pullSecret: ngc-secret
  storage:
    pvc:
      create: true
      size: 50Gi
      storageClass: gp3-csi
      volumeAccessMode: ReadWriteOnce
  tolerations:
    - effect: NoSchedule
      key: g6e-gpu
      operator: Exists
