apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: llama-3-2-nv-embedqa-1b-v2
  namespace: xieshen-nim
spec:
  resources:
    cpu: '0'
    memory: '0'
  source:
    ngc:
      authSecret: ngc-api-secret
      model:
        profiles:
          - 77b5b9d6572c92559ee563f0b219b458520978180f69473cc9ebc2c97a804d11
      modelPuller: 'nvcr.io/nim/nvidia/llama-3.2-nv-embedqa-1b-v2:1.10'
      pullSecret: ngc-secret
  storage:
    pvc:
      create: true
      size: 50Gi
      storageClass: gp3-csi
      volumeAccessMode: ReadWriteOnce
  tolerations:
    - effect: NoSchedule
      key: g6e-gpu
      operator: Exists
