apiVersion: apps.nvidia.com/v1alpha1
kind: NemoGuardrail
metadata:
  labels:
    "app.kubernetes.io/name": "nemo-guardrail"
    "app.kubernetes.io/instance": "nemo-guardrail"
  annotations:
    "openshift.io/scc": "nonroot"
  name: nemo-guardrail
  namespace: nemo-service
spec:
  authSecret: ngc-api-secret
  configStore:
    configMap: gr-config
  env:
    - name: POETRY_VIRTUALENVS_CREATE
      value: "false"
  expose:
    ingress:
      spec: {}
    service:
      port: 8000
      type: ClusterIP
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/xiezhang7/nemoguardrails-nim-test
    tag: latest
  replicas: 1
  livenessProbe:
    enabled: true
    probe:
      httpGet:
        path: /v1/rails/configs
        port: 8000
      initialDelaySeconds: 5
      timeoutSeconds: 30
  readinessProbe:
    enabled: true
    probe:
      httpGet:
        path: /v1/rails/configs
        port: 8000
      initialDelaySeconds: 5
      timeoutSeconds: 30
  startupProbe:
    enabled: true
    probe:
      httpGet:
        path: /v1/rails/configs
        port: 8000
      initialDelaySeconds: 5
      timeoutSeconds: 30

